### ISSUE TITLE
Success rate and hyperparameters of CHER on FetchSlide

### ISSUE THREAD

**Issue by nikisim** [YangRui2015/Modular_HER#2]
Hi!

FSLight1996/SHER told me that I should ask you about hyperparameters for CHER on FetchSlide environment cause your internship Tencent AI Lab(CHER's first author institution).

Have you tried launching the CHER algorithm on the FetchSlide-v1 environment? Did you get a good result? And if so, could you share hyperparameters for CHER on FetchSlide?
I have only achieved about 50% of success on FetchSlide. Could you help, please?

Thanks

**Comment by YangRui2015** [comment]
Hi, 

Thank you for reaching out. I tried CHER on these tasks and the result is similar to yours (around 0.53). 
CHER is not primarily tuned on these tasks. You may need to tune lambda and related parameters in this file https://github.com/mengf1/CHER/blob/master/baselines/cher/config_curriculum.py.

If it dose not work, you may need to contact Prof. Fang (https://mengf1.github.io) for further discussion.

**Comment by nikisim** [comment]
Thank you for the fast response!

Yes, I am trying to tune lambda and batch size right now. It slightly improves outcomes.
I have seen several papers, where CHER performs well on FetchSlide. In particular, in the Soft HER paper(https://arxiv.org/abs/2002.02089) CHER shows better results (success rate is around 0.65). And I am trying to reach it.

Thanks for your help again.
